RegMode="Redirect" # available values: "Patch", "Virtualize", "Redirect"

[reg]
'HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Internet Download Manager'={redirect=""}


'HKEY_CURRENT_USER\SOFTWARE\DownloadManager'={redirect=""}
